### ISSUE TITLE
Portfolio review/comments

### ISSUE THREAD

**Issue by LouisaBarrett** [kccrs/Portfolio#7]
This should be a gh-pages site. I don't see a gh-page branch. Go ahead and make it live and we'll come back around and do a design/layout review.

Code review:

Your HTML is well structured,  adjustments to make are:

Instead of using `<br>` tags, add space/margin between paragraphs with CSS. Similarly, rather than using a `<br>` in the middle of a paragraph, it's better to just make a new paragraph tag.

In your "Education" content (and content that share that structure), you've got the dates in the `<aside>` tag without of any sort of wrapping element. Make them a `<p>` or a lower hierarchy header tag, like an `<h4>` or `<h4>`. And, again, use CSS rather than `<br>` tags to add margin to elements.

CSS:

Define font styles once. Currently you're specifying the color and weight for header tags in the "header styles" section, but then below in the "body styles" section you're setting the font-size. A suggestion: make a "typography" or "fonts" section, and define all your font styles there once.

Within your CSS rules, organize your declarations alphabetically (or if there is another way to organize that you prefer, that's fine, just be consistent throughout).

When applying classes, focus on what the layout section structure is rather than what the content is about. Class names like ".education" and ".work-experience" are far too bound to specific content and cannot be reused elsewhere, which will lead to a lot of duplication in your HTML and CSS and will make it more difficult to maintain long-term.

**Comment by kccrs** [comment]
Hi Louisa!

I forgot about the gh-pages!  I meant to add that but then the module ended and my brain went away from this project.    This is all very good advice, thank you.  I have made most of the changes you requested and have pushed up to gh-pages if you want to continue to review the layout.
